import TriplesFinal.Assumptions.Assumptions
import TriplesFinal.Assumptions.Defs
import TriplesFinal.Basic.AllReps
import TriplesFinal.Basic.Defs
import TriplesFinal.Basic.DivisorBound
import TriplesFinal.Basic.Jacobi
import TriplesFinal.Basic.PrimitiveReps
import TriplesFinal.Basic.Reps
import TriplesFinal.Basic.RootCount
import TriplesFinal.Basic.Thue
import TriplesFinal.Families.Choice
import TriplesFinal.Families.Identity
import TriplesFinal.Families.Mult
import TriplesFinal.Families.Reduce
import TriplesFinal.Families.Split
import TriplesFinal.TwoAdic.Defs
import TriplesFinal.TwoAdic.NStar
import TriplesFinal.TwoAdic.Seed
import TriplesFinal.GoodPrimes.BadPrimes
import TriplesFinal.GoodPrimes.Data
import TriplesFinal.GoodPrimes.Properties
import TriplesFinal.GoodPrimes.Reduction
import TriplesFinal.GoodPrimes.Sigma
import TriplesFinal.Prelim.Hyperbola
import TriplesFinal.Prelim.Roots
import TriplesFinal.Prelim.Abel
import TriplesFinal.Prelim.AfBound
import TriplesFinal.Prelim.Beta
import TriplesFinal.Prelim.BetaBound
import TriplesFinal.Prelim.LValue
import TriplesFinal.Prelim.SingularSeries
import TriplesFinal.Prelim.SingularSeriesValue
import TriplesFinal.Prelim.LdProduct
import TriplesFinal.Prelim.LdLower
import TriplesFinal.Prelim.Weight
import TriplesFinal.TypeI.Defs
import TriplesFinal.TypeI.Theorem
import TriplesFinal.Asymptotic.ErrorTerm
import TriplesFinal.Asymptotic.Formula
import TriplesFinal.Asymptotic.CutoffIntegral
import TriplesFinal.Asymptotic.MainTerm
import TriplesFinal.Asymptotic.SmoothSum
import TriplesFinal.Asymptotic.Setup
import TriplesFinal.Asymptotic.SigmaLower
import TriplesFinal.Asymptotic.DyadicPartition
import TriplesFinal.Asymptotic.WeightFourier
import TriplesFinal.Asymptotic.ErrorSetup
import TriplesFinal.Asymptotic.Separation
import TriplesFinal.Asymptotic.ErrorHyp
import TriplesFinal.Asymptotic.ErrorBound
import TriplesFinal.Analysis.DerivBounds
import TriplesFinal.Analysis.FourierDecay
import TriplesFinal.Analysis.MeasureTools
import TriplesFinal.Heegner.Cosets
import TriplesFinal.Heegner.HeegnerPoint
import TriplesFinal.Heegner.Orbits
import TriplesFinal.Heegner.Pairs
import TriplesFinal.Heegner.Qkappa
import TriplesFinal.Heegner.Reduction
import TriplesFinal.Heegner.Stabiliser
import TriplesFinal.Heegner.SymMat
import TriplesFinal.Heegner.Representatives
import TriplesFinal.Poisson.Defs
import TriplesFinal.Poisson.FourierBump
import TriplesFinal.Poisson.HeegnerPoincare
import TriplesFinal.Poisson.HeegnerPoincareIdentity
import TriplesFinal.Poisson.Poisson
import TriplesFinal.Poisson.PoissonDyadic
import TriplesFinal.Poisson.PoissonTail
import TriplesFinal.Poisson.Unfolding
import TriplesFinal.Spectral.Expansion
import TriplesFinal.Spectral.HeegnerSide
import TriplesFinal.Spectral.Hyperbolic
import TriplesFinal.Spectral.LargeSieve
import TriplesFinal.Spectral.Smooth
import TriplesFinal.Spectral.Twist
import TriplesFinal.Spectral.TwistMeasure
import TriplesFinal.Bessel.GammaBounds
import TriplesFinal.Bessel.Integral
import TriplesFinal.Bessel.MellinBarnes
import TriplesFinal.Bessel.Mh
import TriplesFinal.Bessel.Continuity
import TriplesFinal.Bessel.MellinBarnesProof
import TriplesFinal.TypeIProof.Mopt
import TriplesFinal.TypeIProof.Setup
import TriplesFinal.TypeIProof.Psi
import TriplesFinal.TypeIProof.SpecFam
import TriplesFinal.TypeIProof.BJ0
import TriplesFinal.TypeIProof.BJ1
import TriplesFinal.TypeIProof.Gfun
import TriplesFinal.TypeIProof.BlockJ0
import TriplesFinal.TypeIProof.BlockJ0Total
import TriplesFinal.TypeIProof.BlockJ1Main
import TriplesFinal.TypeIProof.BlockRem
import TriplesFinal.TypeIProof.BlockTail
import TriplesFinal.TypeIProof.Combine
import TriplesFinal.TypeIProof.SpectralSide
import TriplesFinal.TypeIProof.SpectralSum
import TriplesFinal.TypeIProof.BlockJ0DI
import TriplesFinal.TypeIProof.Measurability
import TriplesFinal.TypeIProof.DiscreteFamily
import TriplesFinal.TypeIProof.DiscreteSide
import TriplesFinal.TypeIProof.ContinuousFamily
import TriplesFinal.TypeIProof.ContinuousSide
import TriplesFinal.TypeIProof.SizeBounds
import TriplesFinal.TypeIProof.BoundJ0
import TriplesFinal.TypeIProof.SpectralBound
import TriplesFinal.TypeIProof.XiMBound
import TriplesFinal.TypeIProof.FinalAux
import TriplesFinal.TypeIProof.FinalBound
import TriplesFinal.TypeIProof.Theorem61
import TriplesFinal.Main.Deduction
import TriplesFinal.Main

/-!
# Lean formalization of *Sums of two squares in three-term patterns*

This file imports every module of the project. See `README.md` for an overview and `STATUS.md`
for the status of each lemma.
-/
